
import React from 'react';
import { DiagnosisResult } from '../types';

interface ResultDisplayProps {
  result: DiagnosisResult;
  onReset: () => void;
}

const ResultDisplay: React.FC<ResultDisplayProps> = ({ result, onReset }) => {
  const urgencyColors = {
    'Emergency': 'bg-red-600 text-white',
    'Urgent': 'bg-orange-500 text-white',
    'Routine': 'bg-blue-500 text-white',
    'Self-Care': 'bg-green-600 text-white',
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="bg-white rounded-2xl shadow-xl border border-slate-200 overflow-hidden mb-12 print:shadow-none print:border-none">
      <div className="p-6 bg-slate-900 text-white flex justify-between items-center print:bg-white print:text-black print:border-b print:border-slate-300">
        <div>
          <h3 className="text-xl font-bold">Analysis Results</h3>
          <p className="text-slate-400 text-xs print:hidden">Generated by MediScan AI Engine</p>
        </div>
        <div className="flex items-center gap-4">
           <button 
            onClick={handlePrint}
            className="hidden md:flex items-center gap-2 px-3 py-1.5 bg-slate-800 hover:bg-slate-700 text-xs font-semibold rounded-lg transition-colors print:hidden"
          >
            <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z" />
            </svg>
            Print Report
          </button>
          <span className={`px-4 py-1 rounded-full text-xs font-bold uppercase tracking-widest ${urgencyColors[result.urgencyLevel] || 'bg-slate-500'}`}>
            {result.urgencyLevel}
          </span>
        </div>
      </div>

      <div className="p-8 space-y-8">
        <section>
          <h4 className="text-sm font-bold text-slate-400 uppercase tracking-widest mb-3">Summary of Findings</h4>
          <p className="text-lg text-slate-700 leading-relaxed font-medium">
            {result.summary}
          </p>
        </section>

        <section>
          <h4 className="text-sm font-bold text-slate-400 uppercase tracking-widest mb-4">Potential Conditions</h4>
          <div className="grid gap-4">
            {result.possibleConditions.map((condition, idx) => (
              <div key={idx} className="p-4 rounded-xl border border-slate-100 bg-slate-50 hover:border-blue-200 transition-colors">
                <div className="flex justify-between items-start mb-2">
                  <h5 className="font-bold text-slate-800 text-lg">{condition.name}</h5>
                  <span className={`text-[10px] font-bold px-2 py-0.5 rounded uppercase ${
                    condition.likelihood === 'High' ? 'bg-red-100 text-red-600' : 
                    condition.likelihood === 'Moderate' ? 'bg-orange-100 text-orange-600' : 
                    'bg-green-100 text-green-600'
                  }`}>
                    {condition.likelihood} Likelihood
                  </span>
                </div>
                <p className="text-sm text-slate-600">{condition.reasoning}</p>
              </div>
            ))}
          </div>
        </section>

        <section className="grid grid-cols-1 md:grid-cols-2 gap-8">
          <div>
            <h4 className="text-sm font-bold text-blue-600 uppercase tracking-widest mb-4">Immediate Actions</h4>
            <ul className="space-y-3">
              {result.treatmentPlan.immediateSteps.map((step, idx) => (
                <li key={idx} className="flex gap-3 text-sm text-slate-700">
                  <span className="flex-shrink-0 w-5 h-5 rounded-full bg-blue-100 text-blue-600 flex items-center justify-center font-bold text-[10px] mt-0.5">
                    {idx + 1}
                  </span>
                  {step}
                </li>
              ))}
            </ul>
          </div>
          <div>
            <h4 className="text-sm font-bold text-slate-500 uppercase tracking-widest mb-4">Long-term Advice</h4>
            <ul className="space-y-3">
              {result.treatmentPlan.longTermAdvice.map((advice, idx) => (
                <li key={idx} className="flex gap-3 text-sm text-slate-600 italic">
                  <div className="w-1.5 h-1.5 rounded-full bg-slate-300 mt-2 flex-shrink-0"></div>
                  {advice}
                </li>
              ))}
            </ul>
          </div>
        </section>

        <div className="pt-6 border-t border-slate-100 flex flex-col md:flex-row gap-6 items-center justify-between print:mt-12">
          <div className="flex items-start gap-3 bg-red-50 p-4 rounded-xl border border-red-100">
            <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6 text-red-500 flex-shrink-0 print:hidden" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
            </svg>
            <p className="text-xs text-red-800 leading-tight">
              <strong>Medical Disclaimer:</strong> This report is generated by an AI and is intended for informational purposes only. It is not a substitute for professional medical diagnosis, treatment, or advice. Always consult with a qualified physician or healthcare provider regarding any medical condition or emergency.
            </p>
          </div>
          
          <button 
            onClick={onReset}
            className="flex-shrink-0 px-6 py-2 text-sm font-bold text-slate-500 hover:text-slate-800 transition-colors flex items-center gap-2 print:hidden"
          >
            <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
            </svg>
            Start New Assessment
          </button>
        </div>
      </div>
    </div>
  );
};

export default ResultDisplay;
